Repository rakvium/blog, pull requests merged in 2021-10, with the labels that each got.

#58 Improve posts controller spec
  .rubocop.yml
  spec/controllers/posts_controller_spec.rb
Labels: hacktoberfest-accepted

#59 Upgrade Rails to 6.0.4.1
  Gemfile.lock
Labels: dependencies, hacktoberfest-accepted

#60 Update RuboCop to 1.22.1
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/helpers/error_helpers.rb
  app/controllers/graphql_controller.rb
  app/helpers/application_helper.rb
  app/services/application_service.rb
  config/initializers/secret_token.rb
  spec/controllers/posts_controller_spec.rb
Labels: dependencies, hacktoberfest-accepted

#61 Make secret keys env settable
  .env.sample
  config/initializers/devise.rb
  config/initializers/secret_token.rb
Labels: bug, hacktoberfest-accepted

#62 Update en.yml
  config/locales/en.yml
Labels: enhancement, hacktoberfest-accepted

#63 Update ru.yml
  config/locales/ru.yml
Labels: enhancement, hacktoberfest-accepted

#64 Update en.yml
  config/locales/en.yml
Labels: enhancement, hacktoberfest-accepted

#66 Create fr.yml
  config/locales/fr.yml
Labels: enhancement, hacktoberfest-accepted

#65 Update uk.yml
  config/locales/uk.yml
Labels: enhancement, hacktoberfest-accepted
