Repository rakvium/blog, pull requests merged in 2022-10, with the labels that each got.

#89 Add test for available locales
  Gemfile
  Gemfile.lock
  config/application.rb
  spec/locales/internationalization_spec.rb
Labels: enhancement

#95 feat: German translation
  config/application.rb
  config/locales/de.yml
Labels: hacktoberfest-accepted

#98 Update uk.yml
  config/locales/uk.yml
Labels: hacktoberfest-accepted

#99 Update fr.yml
  config/locales/fr.yml
Labels: hacktoberfest-accepted

#100 Update de.yml
  config/locales/de.yml
Labels: hacktoberfest-accepted

#101 Fix indentation issue for authentication translations
  config/locales/de.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/uk.yml
Labels: bug

#103 Fixed: 200~Merge en.bootstrap.yml contents into en.ym
  config/locales/en.bootstrap.yml
  config/locales/en.yml
Labels: hacktoberfest-accepted

#104 Upgrade Ruby version to 2.7.6
  Gemfile
  Gemfile.lock
Labels: enhancement, hacktoberfest-accepted

#109 Adding Spanish locale to support Spanish language
  config/application.rb
  config/locales/es.yml
Labels: hacktoberfest-accepted
