Repository rakvium/blog, pull requests merged in 2023-10, with the labels that each got.

#130 Add #StandWithUkraine badge to the project
  README.md
Labels: enhancement, hacktoberfest-accepted

#132 Update README.md
  README.md
Labels: hacktoberfest-accepted

#136 Update README.md
  README.md
Labels: hacktoberfest-accepted

#140 Deleted travis.yml
  .travis.yml
Labels: hacktoberfest-accepted

#139 Upgrade Ruby version to 3.0.6
  .github/workflows/ruby.yml
  .tool-versions
  Dockerfile
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/entities/posts.rb
  app/controllers/api/v1/entities/users.rb
Labels: enhancement, hacktoberfest-accepted

#143 Upgrade Rails to 6.1.7.6
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: enhancement, dependencies

#144 Update .ruby-version file
  .ruby-version
Labels: bug, dependencies, hacktoberfest-accepted

#145 Ensure producing unique user emails for tests
  spec/factories/users.rb
Labels: bug

#146 Update users.rb
  app/controllers/api/v1/entities/users.rb
Labels: bug, hacktoberfest-accepted
